### ISSUE TITLE
Values in significant CP change notification emails are wrong

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#929]
e.g.:
![image](https://github.com/user-attachments/assets/1d3ecb55-aec4-4ed4-a5ce-afd0bd865817)

If you go to [the question](https://www.metaculus.com/questions/2788/before-2025-will-laws-be-in-place-requiring-that-ai-systems-that-emulate-humans-must-reveal-to-people-that-they-are-ai/):
- CP value on 2024-09-09 was 40%
- CP value when I got the email (2024-10-10) was 32%
(also the graph is empty, I assume that's unrelated.)

Other examples from 2024-10-07:
![image](https://github.com/user-attachments/assets/e9bb3b05-c3f2-429c-bbaf-22efc58798b5)
![image](https://github.com/user-attachments/assets/2d4d5467-9191-4620-a2c1-292fd02d668c)
![image](https://github.com/user-attachments/assets/773f5bfa-8ae2-4faf-a47b-287bfa511072)

And a group also from 2024-10-07:
![image](https://github.com/user-attachments/assets/32dcebab-871e-4642-a410-92a633526e99)
Here the movement is lacking a direction, and also it's literally impossible for all those options to have moved 38%.

**Comment by SylvainChevalier** [comment]
Consider adding unit tests for CP changes.

**Comment by lsabor** [comment]
I've added unit tests for movement, and both the sorting and the display evaluations seem to be correct.
I've minorly edited the email html to add 2 decimals of precision to percentage displays as well as include + / - symbols.
I checked a few instances manually, and the evaluation seems to be correct. I've also added a mention of when the baseline moment was because it is completely missing on group / MC post notifications.

So it seems to me like the bugs around evaluation have been fixed, but clarity is still pretty poor. 
@SylvainChevalier can you QA the results on the next batch (starting in about an hour from now) of notifications you receive?

**Comment by SylvainChevalier** [comment]
Still broken.
![image](https://github.com/user-attachments/assets/42ffa3ac-9f14-4930-b9ee-6fc7d09a29cb)
from [this question](https://dev.metaculus.com/questions/19920/what-will-the-end-of-year-unemployment-rate-in-south-africa-be-according-to-the-q4-qlfs-report-in-the-following-years/)
Problems:
- 2023 is resolved so can't have a movement
- 2024 moved from 32 to 50
- 2025 moved from 34 to 50
- 2026 had no forecast before I made mine.

Also this one:
![image](https://github.com/user-attachments/assets/97d38942-55a7-4a45-9e0f-3d425634e38f)
from [this question](https://dev.metaculus.com/questions/23534/when-will-we-remove-the-last-piece-of-angular-code/).
Image is broken and there's no change text.

**Comment by lsabor** [comment]
Ahhh, I think I might have figured it out. There was a for loop error where a variable inside the loop was named the same as one outside the loop and thus carried over between loops. It's really weird, but i actually think it explains all of the discrepencies. Making that change and then we'll need another round of QA.

**Comment by lsabor** [comment]
Not deployed to production, but successfully deployed to dev. @SylvainChevalier keep your eyes out for emails.

**Comment by lsabor** [comment]
By the way, [this question](https://dev.metaculus.com/questions/23534/when-will-we-remove-the-last-piece-of-angular-code/) is private or something. I can't view it. I think the snapshot service fails because it doesn't have permissions. I'm not sure how to handle that. @hlbmtc can you take a look at what's going on with the graph not loading issue?

**Comment by hlbmtc** [comment]
Yeah, previews are broken because screenshoting service acts as anonymous user and does not have access to it. Alternatively we could make private question images available for all

@SylvainChevalier Anyway, probably it makes sense to move to a separate ticket

**Comment by SylvainChevalier** [comment]
> the snapshot service fails because it doesn't have permissions
Ah yes, forgot about that. Let's ignore it for now.

> make private question images available for all
Veto.

**Comment by nangchrys** [comment]
Significant change email for [this date question](https://www.metaculus.com/questions/17447/when-will-a-primarily-ai-made-movie-accomplish-these-types-of-success/) is very wrong:
![image](https://github.com/user-attachments/assets/603d8798-d578-49f3-8616-e1485fc81810)
I also have predicted on all subquestions.

**Comment by hlbmtc** [comment]
@lsabor Could you please take a look ^?

**Comment by lsabor** [comment]
Date questions display fixed.

**Comment by lsabor** [comment]
@SylvainChevalier I haven't heard anything about the emails being horribly wrong of late. Can you verify another instance hasn't arisen in the last week or so?

If nothing has come up, I'm going to close this issue.

**Comment by nangchrys** [comment]
A sample from 4 days ago:
![image](https://github.com/user-attachments/assets/ca3d6cf3-9192-43f8-816b-d7b27c1d3f5e)
![image](https://github.com/user-attachments/assets/1c122ce8-8f79-4ed6-a0c8-4ea75e7079c2)
![image](https://github.com/user-attachments/assets/450694ca-93db-43ce-a3c1-83ec65f1e645)

No mention of what the change was:
![image](https://github.com/user-attachments/assets/fbd84f94-636e-453a-b917-2568342afb95)

**Comment by lsabor** [comment]
@nangchrys Thanks for documenting, definitely needs more work

**Comment by lsabor** [comment]
From the look of the email, it looks like the "change" gets written once, and for the rest of the options that don't have change it takes the previous value.
I think I know exactly where in the code that happens, so hopefully it'll be an easy fix.

**Comment by lsabor** [comment]
I think I might have fixed the one where there are incorrect cp change values

I think the missing graph is from a graph summary failure and isn't typical

Unsure about the one without display. Moving back to QA.

**Comment by nangchrys** [comment]
Vaues look good to me.

But I got one of these again:
![image](https://github.com/user-attachments/assets/e5f6a5d0-8e5f-403c-befa-a3d791fa71aa)

And I also think that for group questions only the option that significantly changed should be displayed. But maybe these should have their own issue.

**Comment by lsabor** [comment]
I'm closing this issue and have made another medium priority one (#1473) for the remaining straggling issues, as I think the spirit of this issue is solved (incorrect values in CP change notifications).
